name: webviewx_plus
description: A cross-platform webview using webview_flutter for
  mobile and iFrame for web.
repository: https://github.com/Mahad61/webviewx_plus
version: 0.3.3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  pointer_interceptor: ^0.9.3+4
  uuid: ^3.0.7
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.9.3
  webview_flutter_platform_interface: ^2.5.0
  webview_flutter_wkwebview: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
